# Generated by Django 2.2.10 on 2020-06-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_verbose_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_activity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Buyer'), (1, 'Seller'), (2, 'Agent')], default=0, help_text='Used to redirect logged-in user to the appropriate admin site.'),
        ),
    ]
